#!/bin/bash
# Test trade script - demonstrates the system

echo "🧪 Testing Polymarket Trading System"
echo "===================================="
echo ""
echo "Wallet: 0x141f7D9a6Ab4221F36E21673b43FA751Af37E7eB"
echo ""
echo "Available commands:"
echo ""
echo "1. Scan markets:"
echo "   bun run ./trading-core/market-monitor/scripts/scan.ts"
echo ""
echo "2. Check risk status:"
echo "   bun run ./trading-core/risk-controller/scripts/status.ts"
echo ""
echo "3. View positions:"
echo "   bun run ./trading-core/position-manager/scripts/positions.ts"
echo ""
echo "4. Execute LIVE trade (when opportunity found):"
echo "   bun run ./trading-core/trade-executor/scripts/execute-live.ts --market <id> --direction yes --size 0.5 --edge 3"
echo ""
echo "5. Start 24/7 system:"
echo "   bun run ./trading-core/orchestrator/scripts/run.ts"
echo ""
